pages:
  stage: deploy
  script:
  - curl https://raw.githubusercontent.com/Yonder-Dynamics/wiki-common/master/build_wiki.py | python - .public README.md
  - mkdir public
  - mv .public public
  - find public
  artifacts:
    paths:
    - public
  only:
  - master

