pages:
  stage: deploy
  script:
  - wget https://raw.githubusercontent.com/Yonder-Dynamics/wiki-common/master/build_wiki.py | python - public README.md
  artifacts:
    paths:
    - public
  only:
  - master

