pages:
  stage: deploy
  script:
  - mkdir public
  - cd public
  - wget https://raw.githubusercontent.com/Yonder-Dynamics/wiki-common/master/build_wiki.sh | bash
  artifacts:
    paths:
    - public
  only:
  - master

